### ISSUE TITLE
Fix HOPRd operator

### ISSUE THREAD

**Issue by sitilge** [hoprnet/hoprd-operator#46]
# Description

Currently, the `hoprd` CRD is failing with the following events:

> Error: secret "hoprd-operator-staging" not found

and

> Multi-Attach error for volume "pvc-7634b54b-21e3-497e-87b0-600d1f2644dd" Volume is already used by pod(s) hoprd-operator-staging-controller-7699c6f856-8j8mf

# Related issues

- [ ] Fix creation of `hoprd-operator-staging` secret
- [ ] Fix usage of the proper `accessModes`
- [ ] Update readme with the proper instructions

# Definition of done

The related issues are closed.

# Comments

The first event is straightforward - there is a secret that the pod wants to mount/read from. It should be explained in the docs/readme what exactly is required to be present in the secret.

The second event is most likely related to scheduling problems. So when the PV (physical volume) is already mounted on a node, using RWO (read-write once) access mode, mounting the same PV on another node is not possible. That's what RWO stands for - read-write once = read-write one node. Not pod, but node. So you get this error when then the scheduler tries to schedule the pod on another node, but the node is another geographical location, so you get this event.

Both of these events are flaky and you can get either event depending on the scheduler decisions.

**Comment by ausias-armesto** [comment]
The second wasn't an error of the hoped but a misconfiguration on Rpch. The first no idea that was happening, are you still facing the same problem?
